var wms_layers = [];
var format_points_0 = new ol.format.GeoJSON();
var features_points_0 = format_points_0.readFeatures(json_points_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_points_0 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_points_0.addFeatures(features_points_0);var lyr_points_0 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_points_0, 
                style: style_points_0,
                title: '<img src="styles/legend/points_0.png" /> points'
            });var format_water_issues_1 = new ol.format.GeoJSON();
var features_water_issues_1 = format_water_issues_1.readFeatures(json_water_issues_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_water_issues_1 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_water_issues_1.addFeatures(features_water_issues_1);var lyr_water_issues_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_water_issues_1, 
                style: style_water_issues_1,
                title: '<img src="styles/legend/water_issues_1.png" /> water_issues'
            });var format_hunger_2 = new ol.format.GeoJSON();
var features_hunger_2 = format_hunger_2.readFeatures(json_hunger_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_hunger_2 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_hunger_2.addFeatures(features_hunger_2);var lyr_hunger_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_hunger_2, 
                style: style_hunger_2,
                title: '<img src="styles/legend/hunger_2.png" /> hunger'
            });var format_spouse_neg_3 = new ol.format.GeoJSON();
var features_spouse_neg_3 = format_spouse_neg_3.readFeatures(json_spouse_neg_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_spouse_neg_3 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_spouse_neg_3.addFeatures(features_spouse_neg_3);var lyr_spouse_neg_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_spouse_neg_3, 
                style: style_spouse_neg_3,
                title: '<img src="styles/legend/spouse_neg_3.png" /> spouse_neg'
            });var format_spouse_pos_4 = new ol.format.GeoJSON();
var features_spouse_pos_4 = format_spouse_pos_4.readFeatures(json_spouse_pos_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_spouse_pos_4 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_spouse_pos_4.addFeatures(features_spouse_pos_4);var lyr_spouse_pos_4 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_spouse_pos_4, 
                style: style_spouse_pos_4,
                title: '<img src="styles/legend/spouse_pos_4.png" /> spouse_pos'
            });var format_people_neg_5 = new ol.format.GeoJSON();
var features_people_neg_5 = format_people_neg_5.readFeatures(json_people_neg_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_people_neg_5 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_people_neg_5.addFeatures(features_people_neg_5);var lyr_people_neg_5 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_people_neg_5, 
                style: style_people_neg_5,
                title: '<img src="styles/legend/people_neg_5.png" /> people_neg'
            });var format_people_pos_6 = new ol.format.GeoJSON();
var features_people_pos_6 = format_people_pos_6.readFeatures(json_people_pos_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_people_pos_6 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_people_pos_6.addFeatures(features_people_pos_6);var lyr_people_pos_6 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_people_pos_6, 
                style: style_people_pos_6,
                title: '<img src="styles/legend/people_pos_6.png" /> people_pos'
            });var format_animals_neg_7 = new ol.format.GeoJSON();
var features_animals_neg_7 = format_animals_neg_7.readFeatures(json_animals_neg_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_animals_neg_7 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_animals_neg_7.addFeatures(features_animals_neg_7);var lyr_animals_neg_7 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_animals_neg_7, 
                style: style_animals_neg_7,
                title: '<img src="styles/legend/animals_neg_7.png" /> animals_neg'
            });var format_r_animals_pos_8 = new ol.format.GeoJSON();
var features_r_animals_pos_8 = format_r_animals_pos_8.readFeatures(json_r_animals_pos_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_r_animals_pos_8 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_r_animals_pos_8.addFeatures(features_r_animals_pos_8);var lyr_r_animals_pos_8 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_r_animals_pos_8, 
                style: style_r_animals_pos_8,
                title: '<img src="styles/legend/r_animals_pos_8.png" /> r_animals_pos'
            });var format_nature_neg_9 = new ol.format.GeoJSON();
var features_nature_neg_9 = format_nature_neg_9.readFeatures(json_nature_neg_9, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_nature_neg_9 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_nature_neg_9.addFeatures(features_nature_neg_9);var lyr_nature_neg_9 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_nature_neg_9, 
                style: style_nature_neg_9,
                title: '<img src="styles/legend/nature_neg_9.png" /> nature_neg'
            });var format_nature_pos_10 = new ol.format.GeoJSON();
var features_nature_pos_10 = format_nature_pos_10.readFeatures(json_nature_pos_10, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_nature_pos_10 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_nature_pos_10.addFeatures(features_nature_pos_10);var lyr_nature_pos_10 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_nature_pos_10, 
                style: style_nature_pos_10,
                title: '<img src="styles/legend/nature_pos_10.png" /> nature_pos'
            });var format_negative_11 = new ol.format.GeoJSON();
var features_negative_11 = format_negative_11.readFeatures(json_negative_11, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_negative_11 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_negative_11.addFeatures(features_negative_11);var lyr_negative_11 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_negative_11, 
                style: style_negative_11,
                title: '<img src="styles/legend/negative_11.png" /> negative'
            });var format_lines_pos_12 = new ol.format.GeoJSON();
var features_lines_pos_12 = format_lines_pos_12.readFeatures(json_lines_pos_12, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_lines_pos_12 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_lines_pos_12.addFeatures(features_lines_pos_12);var lyr_lines_pos_12 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_lines_pos_12, 
                style: style_lines_pos_12,
                title: '<img src="styles/legend/lines_pos_12.png" /> lines_pos'
            });var format_namescopycopy_13 = new ol.format.GeoJSON();
var features_namescopycopy_13 = format_namescopycopy_13.readFeatures(json_namescopycopy_13, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_namescopycopy_13 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_namescopycopy_13.addFeatures(features_namescopycopy_13);var lyr_namescopycopy_13 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_namescopycopy_13, 
                style: style_namescopycopy_13,
                title: '<img src="styles/legend/namescopycopy_13.png" /> names copy copy'
            });var format_nickname_14 = new ol.format.GeoJSON();
var features_nickname_14 = format_nickname_14.readFeatures(json_nickname_14, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_nickname_14 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_nickname_14.addFeatures(features_nickname_14);var lyr_nickname_14 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_nickname_14, 
                style: style_nickname_14,
                title: 'nickname'
            });var format_names_15 = new ol.format.GeoJSON();
var features_names_15 = format_names_15.readFeatures(json_names_15, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_names_15 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_names_15.addFeatures(features_names_15);var lyr_names_15 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_names_15, 
                style: style_names_15,
                title: 'names'
            });var format_landowner_16 = new ol.format.GeoJSON();
var features_landowner_16 = format_landowner_16.readFeatures(json_landowner_16, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_landowner_16 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_landowner_16.addFeatures(features_landowner_16);var lyr_landowner_16 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_landowner_16, 
                style: style_landowner_16,
                title: '<img src="styles/legend/landowner_16.png" /> landowner'
            });var format_freestanding_17 = new ol.format.GeoJSON();
var features_freestanding_17 = format_freestanding_17.readFeatures(json_freestanding_17, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_freestanding_17 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_freestanding_17.addFeatures(features_freestanding_17);var lyr_freestanding_17 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_freestanding_17, 
                style: style_freestanding_17,
                title: '<img src="styles/legend/freestanding_17.png" /> free standing'
            });var format_hunters_18 = new ol.format.GeoJSON();
var features_hunters_18 = format_hunters_18.readFeatures(json_hunters_18, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_hunters_18 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_hunters_18.addFeatures(features_hunters_18);var lyr_hunters_18 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_hunters_18, 
                style: style_hunters_18,
                title: '<img src="styles/legend/hunters_18.png" /> hunters'
            });var format_peasants_19 = new ol.format.GeoJSON();
var features_peasants_19 = format_peasants_19.readFeatures(json_peasants_19, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_peasants_19 = new ol.source.Vector({
    attributions: '<a href=""></a>',
});
jsonSource_peasants_19.addFeatures(features_peasants_19);var lyr_peasants_19 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_peasants_19, 
                style: style_peasants_19,
                title: '<img src="styles/legend/peasants_19.png" /> peasants'
            });

lyr_points_0.setVisible(true);lyr_water_issues_1.setVisible(true);lyr_hunger_2.setVisible(true);lyr_spouse_neg_3.setVisible(true);lyr_spouse_pos_4.setVisible(true);lyr_people_neg_5.setVisible(true);lyr_people_pos_6.setVisible(true);lyr_animals_neg_7.setVisible(true);lyr_r_animals_pos_8.setVisible(true);lyr_nature_neg_9.setVisible(true);lyr_nature_pos_10.setVisible(true);lyr_negative_11.setVisible(true);lyr_lines_pos_12.setVisible(true);lyr_namescopycopy_13.setVisible(true);lyr_nickname_14.setVisible(false);lyr_names_15.setVisible(false);lyr_landowner_16.setVisible(true);lyr_freestanding_17.setVisible(true);lyr_hunters_18.setVisible(true);lyr_peasants_19.setVisible(true);
var layersList = [lyr_points_0,lyr_water_issues_1,lyr_hunger_2,lyr_spouse_neg_3,lyr_spouse_pos_4,lyr_people_neg_5,lyr_people_pos_6,lyr_animals_neg_7,lyr_r_animals_pos_8,lyr_nature_neg_9,lyr_nature_pos_10,lyr_negative_11,lyr_lines_pos_12,lyr_namescopycopy_13,lyr_nickname_14,lyr_names_15,lyr_landowner_16,lyr_freestanding_17,lyr_hunters_18,lyr_peasants_19];
lyr_points_0.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_water_issues_1.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_hunger_2.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_spouse_neg_3.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_spouse_pos_4.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_people_neg_5.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_people_pos_6.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_animals_neg_7.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_r_animals_pos_8.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_nature_neg_9.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_nature_pos_10.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_negative_11.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_lines_pos_12.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_namescopycopy_13.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_nickname_14.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_names_15.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_landowner_16.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_freestanding_17.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_hunters_18.set('fieldAliases', {'ogc_fid': 'ogc_fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_peasants_19.set('fieldAliases', {'ogc_fid': 'ogc_fid', 'fid': 'fid', '_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_points_0.set('fieldImages', {'ogc_fid': '', '_': '', 'character name (may be an animal too)': '', 'location': '', 'y': '', 'x': '', 'gender': '', 'story where s/he mentioned': '', 'nickname (if applicable)': '', 'employed or unemployed': '', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': '', 'x_to': '', 'y_to': '', 'relation to another character': '', 'sentiment': '', 'quotation': '', 'family status': '', 'children': '', 'relation to spouse': '', 'quotation_1': '', 'relation to people': '', 'quotations (always a complete sentence)': '', 'people_s relation to the character': '', 'quotations': '', 'relations to animals': '', 'quotations_1': '', 'relations to nature': '', 'quotations_2': '', 'hunger issue': '', 'water issue': '', });
lyr_water_issues_1.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_hunger_2.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_spouse_neg_3.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_spouse_pos_4.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_people_neg_5.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_people_pos_6.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_animals_neg_7.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_r_animals_pos_8.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_nature_neg_9.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_nature_pos_10.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_negative_11.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_lines_pos_12.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_namescopycopy_13.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_nickname_14.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_names_15.set('fieldImages', {'ogc_fid': 'Hidden', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'Hidden', 'y': 'ValueMap', 'x': 'ValueMap', 'gender': 'Hidden', 'story where s/he mentioned': 'Hidden', 'nickname (if applicable)': 'Hidden', 'employed or unemployed': 'Hidden', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'Hidden', 'x_to': 'Hidden', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_landowner_16.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_freestanding_17.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_hunters_18.set('fieldImages', {'ogc_fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_peasants_19.set('fieldImages', {'ogc_fid': 'TextEdit', 'fid': 'TextEdit', '_': 'Range', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_points_0.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_water_issues_1.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_hunger_2.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_spouse_neg_3.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_spouse_pos_4.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_people_neg_5.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_people_pos_6.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_animals_neg_7.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_r_animals_pos_8.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_nature_neg_9.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_nature_pos_10.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_negative_11.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_lines_pos_12.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_namescopycopy_13.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_nickname_14.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_names_15.set('fieldLabels', {'_': 'inline label', 'character name (may be an animal too)': 'no label', 'y': 'no label', 'x': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'inline label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_landowner_16.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_freestanding_17.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_hunters_18.set('fieldLabels', {'ogc_fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_peasants_19.set('fieldLabels', {'ogc_fid': 'no label', 'fid': 'no label', '_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_peasants_19.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});