var wms_layers = [];
var format_hunger_0 = new ol.format.GeoJSON();
var features_hunger_0 = format_hunger_0.readFeatures(json_hunger_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_hunger_0 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_hunger_0.addFeatures(features_hunger_0);var lyr_hunger_0 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_hunger_0, 
                style: style_hunger_0,
                title: '<img src="styles/legend/hunger_0.png" /> hunger'
            });var format_water_1 = new ol.format.GeoJSON();
var features_water_1 = format_water_1.readFeatures(json_water_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_water_1 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_water_1.addFeatures(features_water_1);var lyr_water_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_water_1, 
                style: style_water_1,
                title: '<img src="styles/legend/water_1.png" /> water'
            });var format_bad_2 = new ol.format.GeoJSON();
var features_bad_2 = format_bad_2.readFeatures(json_bad_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_bad_2 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_bad_2.addFeatures(features_bad_2);var lyr_bad_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_bad_2, 
                style: style_bad_2,
                title: '<img src="styles/legend/bad_2.png" /> bad'
            });var format_good_3 = new ol.format.GeoJSON();
var features_good_3 = format_good_3.readFeatures(json_good_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_good_3 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_good_3.addFeatures(features_good_3);var lyr_good_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_good_3, 
                style: style_good_3,
                title: '<img src="styles/legend/good_3.png" /> good'
            });var format_lord_4 = new ol.format.GeoJSON();
var features_lord_4 = format_lord_4.readFeatures(json_lord_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_lord_4 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_lord_4.addFeatures(features_lord_4);var lyr_lord_4 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_lord_4, 
                style: style_lord_4,
                title: '<img src="styles/legend/lord_4.png" /> lord'
            });var format_selfemplself_emplPoint_5 = new ol.format.GeoJSON();
var features_selfemplself_emplPoint_5 = format_selfemplself_emplPoint_5.readFeatures(json_selfemplself_emplPoint_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_selfemplself_emplPoint_5 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_selfemplself_emplPoint_5.addFeatures(features_selfemplself_emplPoint_5);var lyr_selfemplself_emplPoint_5 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_selfemplself_emplPoint_5, 
                style: style_selfemplself_emplPoint_5,
                title: '<img src="styles/legend/selfemplself_emplPoint_5.png" /> self-empl self_empl Point'
            });var format_hu_6 = new ol.format.GeoJSON();
var features_hu_6 = format_hu_6.readFeatures(json_hu_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_hu_6 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_hu_6.addFeatures(features_hu_6);var lyr_hu_6 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_hu_6, 
                style: style_hu_6,
                title: '<img src="styles/legend/hu_6.png" /> hu'
            });var format_pea_7 = new ol.format.GeoJSON();
var features_pea_7 = format_pea_7.readFeatures(json_pea_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_pea_7 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_pea_7.addFeatures(features_pea_7);var lyr_pea_7 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_pea_7, 
                style: style_pea_7,
                title: '<img src="styles/legend/pea_7.png" /> pea'
            });var format_names__8 = new ol.format.GeoJSON();
var features_names__8 = format_names__8.readFeatures(json_names__8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_names__8 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_names__8.addFeatures(features_names__8);var lyr_names__8 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_names__8, 
                style: style_names__8,
                title: '<img src="styles/legend/names__8.png" /> names_'
            });

lyr_hunger_0.setVisible(true);lyr_water_1.setVisible(true);lyr_bad_2.setVisible(true);lyr_good_3.setVisible(true);lyr_lord_4.setVisible(true);lyr_selfemplself_emplPoint_5.setVisible(true);lyr_hu_6.setVisible(true);lyr_pea_7.setVisible(true);lyr_names__8.setVisible(true);
var layersList = [lyr_hunger_0,lyr_water_1,lyr_bad_2,lyr_good_3,lyr_lord_4,lyr_selfemplself_emplPoint_5,lyr_hu_6,lyr_pea_7,lyr_names__8];
lyr_hunger_0.set('fieldAliases', {'_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_water_1.set('fieldAliases', {'_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_bad_2.set('fieldAliases', {'_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_good_3.set('fieldAliases', {'_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_lord_4.set('fieldAliases', {'_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_selfemplself_emplPoint_5.set('fieldAliases', {'_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_hu_6.set('fieldAliases', {'_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_pea_7.set('fieldAliases', {'_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_names__8.set('fieldAliases', {'_': '_', 'character name (may be an animal too)': 'character name (may be an animal too)', 'location': 'location', 'y': 'y', 'x': 'x', 'gender': 'gender', 'story where s/he mentioned': 'story where s/he mentioned', 'nickname (if applicable)': 'nickname (if applicable)', 'employed or unemployed': 'employed or unemployed', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)', 'x_to': 'x_to', 'y_to': 'y_to', 'relation to another character': 'relation to another character', 'sentiment': 'sentiment', 'quotation': 'quotation', 'family status': 'family status', 'children': 'children', 'relation to spouse': 'relation to spouse', 'quotation_1': 'quotation_1', 'relation to people': 'relation to people', 'quotations (always a complete sentence)': 'quotations (always a complete sentence)', 'people_s relation to the character': 'people_s relation to the character', 'quotations': 'quotations', 'relations to animals': 'relations to animals', 'quotations_1': 'quotations_1', 'relations to nature': 'relations to nature', 'quotations_2': 'quotations_2', 'hunger issue': 'hunger issue', 'water issue': 'water issue', });
lyr_hunger_0.set('fieldImages', {'_': 'TextEdit', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_water_1.set('fieldImages', {'_': 'TextEdit', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_bad_2.set('fieldImages', {'_': 'TextEdit', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_good_3.set('fieldImages', {'_': 'TextEdit', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_lord_4.set('fieldImages', {'_': 'TextEdit', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_selfemplself_emplPoint_5.set('fieldImages', {'_': 'TextEdit', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_hu_6.set('fieldImages', {'_': 'TextEdit', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_pea_7.set('fieldImages', {'_': 'TextEdit', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_names__8.set('fieldImages', {'_': 'TextEdit', 'character name (may be an animal too)': 'TextEdit', 'location': 'TextEdit', 'y': 'TextEdit', 'x': 'TextEdit', 'gender': 'TextEdit', 'story where s/he mentioned': 'TextEdit', 'nickname (if applicable)': 'TextEdit', 'employed or unemployed': 'TextEdit', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'TextEdit', 'x_to': 'TextEdit', 'y_to': 'TextEdit', 'relation to another character': 'TextEdit', 'sentiment': 'TextEdit', 'quotation': 'TextEdit', 'family status': 'TextEdit', 'children': 'TextEdit', 'relation to spouse': 'TextEdit', 'quotation_1': 'TextEdit', 'relation to people': 'TextEdit', 'quotations (always a complete sentence)': 'TextEdit', 'people_s relation to the character': 'TextEdit', 'quotations': 'TextEdit', 'relations to animals': 'TextEdit', 'quotations_1': 'TextEdit', 'relations to nature': 'TextEdit', 'quotations_2': 'TextEdit', 'hunger issue': 'TextEdit', 'water issue': 'TextEdit', });
lyr_hunger_0.set('fieldLabels', {'_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_water_1.set('fieldLabels', {'_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_bad_2.set('fieldLabels', {'_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_good_3.set('fieldLabels', {'_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_lord_4.set('fieldLabels', {'_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_selfemplself_emplPoint_5.set('fieldLabels', {'_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_hu_6.set('fieldLabels', {'_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_pea_7.set('fieldLabels', {'_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_names__8.set('fieldLabels', {'_': 'no label', 'character name (may be an animal too)': 'no label', 'location': 'no label', 'y': 'no label', 'x': 'no label', 'gender': 'no label', 'story where s/he mentioned': 'no label', 'nickname (if applicable)': 'no label', 'employed or unemployed': 'no label', 'type of employment (e.g. peasant, rent_paying peasant, landowner etc)': 'no label', 'x_to': 'no label', 'y_to': 'no label', 'relation to another character': 'no label', 'sentiment': 'no label', 'quotation': 'no label', 'family status': 'no label', 'children': 'no label', 'relation to spouse': 'no label', 'quotation_1': 'no label', 'relation to people': 'no label', 'quotations (always a complete sentence)': 'no label', 'people_s relation to the character': 'no label', 'quotations': 'no label', 'relations to animals': 'no label', 'quotations_1': 'no label', 'relations to nature': 'no label', 'quotations_2': 'no label', 'hunger issue': 'no label', 'water issue': 'no label', });
lyr_names__8.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});